### ISSUE TITLE
Question about running

### ISSUE THREAD

**Issue by 2knarf** [captainbeeheart/pypn5180#1]
Hi, it does not look like i can to the FREEDUMP?
```

nuc ~ # python3 -m pypn5180.pypn5180_15693 FREEDUMP -f 2
Connecting to PN5180 device...
Conected to FTDI SPI ftdi://ftdi:2232h/2
PN5180 Self test:
 Firmware version: 0x305
 Product Version : 0x305
 EEPROM version  : 0x9100
 Die identifier  : b'0000000000017c0a6f213ca922364051'

Configuring device for ISO IEC 15693
[Transaction OK] SysInfo - chip serial: 'c42a330100a407e0'
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/pypn5180-1.0-py3.7.egg/pypn5180/pypn5180_15693.py", line 86, in <module>
NameError: name 'dumpFREE' is not defined

```

**Comment by captainbeeheart** [comment]
Hi Frank,
It seems your PN5180 board is not responding (All versions and die identifiers to FFFF).
Try to add "--ftdi_port PORT_B" to the command line, as you may have connected the second channel of FTDI chip. If still not working, re-check the connections between FTDI chip and PN5180 boards.
Check also that RST pin of PN5180 is connected to 3V3, this may cause the issue too.

Then, on the command, FREEDUMP will not work. My mistake... I split this tool in two parts. New tool will be dedicated to freestyle FRAM dump and data display (like temp, glycemian...). FREEDUMP has been moved in the new tool that I'll release soon. The 'DUMP' command is however valid but will dump full FRAM raw data to a file.

So try:
python3 -m pypn5180.pypn5180_15693 DUMP --ftdi_port PORT_B

BR
Cap'

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by triplepurple** [comment]
Greetings Captainbeehart,
   
    I was looking into your github code using the pn5180 product and have tried to run it on my Pi but have been unable to get it to work i was wondering if you would be able to answer a couple questions for me.

        * what kind of version of pi did you use (1,2,3,zero)
       
        * what os what it running (stretch or buster)

        * how did you enable the spidev  my /boot/config.txt  has  dtparam=spi=on and dtoverlay=sc16is752-spi1

        * was there any other settings that i need to change

again any help you could provide would greatly appreciated thank you for you time and if there is any info i need to provide you with please let me know
                                                                                                                   
                                        Alexis
