### ISSUE TITLE
Error on getting PN5180 to work with FT232H

### ISSUE THREAD

**Issue by ekawahyu** [captainbeeheart/pypn5180#2]
I made a simple work around as "PORT_C" that recognizes FT232H url. It may not be correct the way I do it, could you refer me to the proper way to support FT232H chip?

Below is the error message:

```
Connecting to PN5180 device...
Conected to FTDI SPI ftdi://ftdi:232h:1:d/1
PN5180 Self test:
 Firmware version: 0xffff
 Product Version : 0xffff
 EEPROM version  : 0xffff
 Die identifier  : b'ffffffffffffffffffffffffffffffff'

Configuring device for ISO IEC 15693
transactionIsoIec15693 Error in RF state: WAIT_RECEIVE
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/Sync/git/ekawahyu/pypn5180/pypn5180/pypn5180_15693.py", line 71, in <module>
    sys_info, errStr = isoIec15693.getSystemInformationCmd()
  File "/home/ubuntu/Sync/git/ekawahyu/pypn5180/pypn5180/iso_iec_15693.py", line 245, in getSystemInformationCmd
    flags, data = self.pn5180.transactionIsoIec15693(frame)
TypeError: cannot unpack non-iterable int object
```

**Comment by ekawahyu** [comment]
So, one of the other thing that I tried, is resetting PN5180 manually from its RESET pin. And that may actually work as shown below:
```
Connecting to PN5180 device...
Conected to FTDI SPI ftdi://ftdi:232h:1:12/1
PN5180 Self test:
 Firmware version: 0x305
 Product Version : 0x305
 EEPROM version  : 0x9100
 Die identifier  : b'0000000000017c0a61413ca922364051'

Configuring device for ISO IEC 15693
[Transaction OK] SysInfo - chip serial: 'ba9bd2d1500104e0'
```

My questions remain the same, how can I add support for FT232H the correct way? And one more question, everytime I unplug and plug FT232H back in, the url keeps changing. How can I address FT232H if the url keeps changing like this? Thank you.
